_author_ = 'arichland'

import pylists
import json
count = -1





# Create dicts based upon list of column headers from pylist.py
# Dicts consist of column header and column number
analysis_dict ={}
list = pylists.analysis_headers
count = -1
dic = dict()
for ele in list:
    count = count + 1
    dic[ele] = count
analysis_dict = json.dumps(dic, indent=1)
#print("analysis_dict", str(analysis_dict))


inven_hist_dict ={}
list = pylists.inven_hist_headers
count = -1
dic = dict()
for ele in list:
    count = count + 1
    dic[ele] = count
inven_hist_dict = json.dumps(dic, indent=1)
#print("inven_hist",str(inven_hist_dict))



sql_dict = {
    'user': 'admin',
    'password': 'RichlanD053009',
    'host': 'rtc-aws-01.capevptjfomy.us-east-2.rds.amazonaws.com',
    'database': 'rtcaws01',
    'charset': 'utf8mb4'
}


# Formulas by Sheet
analysis ={'''
'Concat': "=IFERROR(VLOOKUP(B3,'Material Data'!A:B,2,FALSE), 0)",
'Material': "=IFERROR(VLOOKUP(B3,'Material Data'!A:B,2,FALSE),"-")",
'Location': "",
'Material Description': "",
'Location Desctiption': "",
'Include?': "",
'Purchased/Produced?':  "",
'Category': "",
'Sub Category': "",
'Abc Class': "",
'Inven Turns': "",
'Avg Days To Turn Inven':  "",
'Velocity Category': "",
'Stock In Months': "",
'Stock Category': "",
'Abc Class Category':  "",
'Unit Price': "",
'Unit Cost': "",
'Current Inventory': "",
'Inventory Value': "",
'Average Inventory': "",
'Average Value': "",
'Annual Volume': "",
'Demand $': "",
'Annual Margin': "",
'Months Active': "",
'Demand Variability': "",
'Fcst Accuracy': "",
'Ss - Demand Variance': "",
'Ss - Forecast Error': "",
'Suggested Ss Method': "",
'Cycle Stock': "",
'Min Inventory': "",
'Max Inventory': "",
'Avg Inventory': "",
'Avg Inventory Value': "",
'Diff Vs Current': "",
'''}

# Excel functions supported in Openpyxl

analysis_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Material Description': 'E3',
    'Location Desctiption': 'F3',
    'Include?': 'G3',
    'Purchased/Produced?': 'H3',
    'Category': 'I3',
    'Sub Category': 'J3',
    'Abc Class': 'K3',
    'Inven Turns': 'L3',
    'Avg Days To Turn Inven': 'M3',
    'Velocity Category': 'N3',
    'Stock In Months': 'O3',
    'Stock Category': 'P3',
    'Abc Class Category': 'Q3',
    'Unit Price': 'R3',
    'Unit Cost': 'S3',
    'Current Inventory': 'T3',
    'Inventory Value': 'U3',
    'Average Inventory': 'V3',
    'Average Value': 'W3',
    'Annual Volume': 'X3',
    'Demand $': 'Y3',
    'Annual Margin': 'Z3',
    'Months Active': 'AA3',
    'Demand Variability': 'AB3',
    'Fcst Accuracy': 'AC3',
    'SS - Demand Variance': 'AD3',
    'SS - Forecast Error': 'AE3',
    'Suggested SS Method': 'AF3',
    'Cycle Stock': 'AG3',
    'Min Inventory': 'AH3',
    'Max Inventory': 'AI3',
    'Avg Inventory': 'AJ3',
    'Avg Inventory Value': 'AK3',
    'Diff vs Current': 'AL3'
}
inven_hist_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Month 01': 'E3',
    'Month 02': 'F3',
    'Month 03': 'G3',
    'Month 04': 'H3',
    'Month 05': 'I3',
    'Month 06': 'J3',
    'Month 07': 'K3',
    'Month 08': 'L3',
    'Month 09': 'M3',
    'Month 10': 'N3',
    'Month 11': 'O3',
    'Month 12': 'P3',
    'Month 13': 'Q3',
    'Month 14': 'R3',
    'Average': 'S3',
    'Min': 'T3',
    'Max': 'U3',
    'Total': 'V3',
    'Months with inventory': 'W3',
    'Avg Inventory when >0': 'X3',
    'Min when >0': 'Y3'
}
cur_inven_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Current Inventory': 'E3',
    'Inventory value': 'F3',
    'COGS': 'G3',
    'Price': 'H3'
}
sales_hist_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Month 01': 'E3',
    'Month 02': 'F3',
    'Month 03': 'G3',
    'Month 04': 'H3',
    'Month 05': 'I3',
    'Month 06': 'J3',
    'Month 07': 'K3',
    'Month 08': 'L3',
    'Month 09': 'M3',
    'Month 10': 'N3',
    'Month 11': 'O3',
    'Month 12': 'P3',
    'Total Demand': 'Q3',
    'Active Months': 'R3',
    'Avg Demand': 'S3',
    'Min': 'T3',
    'Max': 'U3',
    'AVG >0': 'V3',
    'MIN >0': 'W3',
    'Lt': 'X3',
    'Annual': 'Y3',
    'Q1': 'Z3',
    'Q2': 'AA3',
    'Q3': 'AB3',
    'Q4': 'AC3',
    'Annual': 'AD3',
    'Q1': 'AE3',
    'Q2': 'AF3',
    'Q3': 'AG3',
    'Q4': 'AH3',
    'Annual': 'AI3',
    'Q1': 'AJ3',
    'Q2': 'AK3',
    'Q3': 'AL3'
}
forecast_hist_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Month 01A': 'E3',
    'Month 02A': 'F3',
    'Month 03A': 'G3',
    'Month 04A': 'H3',
    'Month 05A': 'I3',
    'Month 06A': 'J3',
    'Month 07A': 'K3',
    'Month 08A': 'L3',
    'Month 09A': 'M3',
    'Month 10A': 'N3',
    'Month 11A': 'O3',
    'Month 12A': 'P3',
    'Month 01B': 'Q3',
    'Month 02B': 'R3',
    'Month 03B': 'S3',
    'Month 04B': 'T3',
    'Month 05B': 'U3',
    'Month 06B': 'V3',
    'Month 07B': 'W3',
    'Month 08B': 'X3',
    'Month 09B': 'Y3',
    'Month 10B': 'Z3',
    'Month 11B': 'AA3',
    'Month 12B': 'AB3',
    'Month 01C': 'AC3',
    'Month 02C': 'AD3',
    'Month 03C': 'AE3',
    'Month 04C': 'AF3',
    'Month 05C': 'AG3',
    'Month 06C': 'AH3',
    'Month 07C': 'AI3',
    'Month 08C': 'AJ3',
    'Month 09C': 'AK3',
    'Month 10C': 'AL3',
    'Month 11C': 'AM3',
    'Month 12C': 'AN3',
    'Total Bias': 'AO3',
    'Month 01D': 'AP3',
    'Month 02D': 'AQ3',
    'Month 03D': 'AR3',
    'Month 04D': 'AS3',
    'Month 05D': 'AT3',
    'Month 06D': 'AU3',
    'Month 07D': 'AV3',
    'Month 08D': 'AW3',
    'Month 09D': 'AX3',
    'Month 10D': 'AY3',
    'Month 11D': 'AZ3',
    'Month 12D': 'BA3',
    'RMSE': 'BB3',
    'RMSE ACTIVE': 'BC3',
    'Month 01E': 'BD3',
    'Month 02E': 'BE3',
    'Month 03E': 'BF3',
    'Month 04E': 'BG3',
    'Month 05E': 'BH3',
    'Month 06E': 'BI3',
    'Month 07E': 'BJ3',
    'Month 08E': 'BK3',
    'Month 09E': 'BL3',
    'Month 10E': 'BM3',
    'Month 11E': 'BN3',
    'Month 12E': 'BO3',
    'SUM OF ERROR %': 'BP3',
    'AVG MAPE1': 'BQ3',
    'Avg Bias1': 'BR3',
    'AVG MAPE2': 'BS3',
    'Avg Bias2': 'BT3',
    'MAD': 'BU3',
    'Tracking Signal': 'BV3',
    'TS': 'BW3',
    'TY Accuracy': 'BX3',
    'Active Accuracy': 'BY3',
    'SS ANNUAL ERROR': 'BZ3',
    'SS ACTIVE ERROR': 'CA3'
}
inven_turn_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Qty On Hand': 'E3',
    'On Hand Value': 'F3',
    'COGS': 'G3',
    'Avg Inven $': 'H3',
    'Inven Turns': 'I3',
    'Days to Turn Inven': 'J3',
    'Velocity Category': 'K3',
    'On Hand Inventory': 'L3',
    'Stock in Months': 'M3',
    'Stock Category': 'N3'
}
segmen_headers = {
    'Concat': 'B3',
    'Sku': 'C3',
    'Loc': 'D3',
    'Segmentation': 'E3',
    'Category Segmentation': 'F3'
}
segmen_calc_headers = {
    'Concat': 'B3',
    'Material': 'C3',
    'Location': 'D3',
    'Category': 'E3',
    'Sub Category': 'F3',
    'Annual Volume': 'G3',
    'Demand $': 'H3',
    'Annual Margin': 'I3',
    'Sku %': 'J3',
    'Cumulative': 'K3'
}
material_headers = {
    'Material': 'B3',
    'Description': 'C3',
    'Unit Cost': 'D3',
    'Currency': 'E3',
    'Unit Price1': 'F3',
    'Category': 'G3',
    'Subcategory': 'H3',
    'Status': 'I3',
    'Unit Price2': 'J3',
    'Units/Case': 'K3',
    'Case/Pallet': 'L3'
}
skus_headers = {
    'ConCat': 'B3',
    'Material': 'C3',
    'Locale': 'D3',
    'Purchasing/Producing?': 'E3'
}
locale_headers = {
    'Location': 'B3',
    'Description': 'C3'
}




xl_functions = {
    'ABS': 'str',
    'ACCRINT': 'str',
    'ACCRINTM': 'str',
    'ACOS': 'str',
    'ACOSH': 'str',
    'AMORDEGRC': 'str',
    'AMORLINC': 'str',
    'AND': 'str',
    'AREAS': 'str',
    'ASC': 'str',
    'ASIN': 'str',
    'ASINH': 'str',
    'ATAN': 'str',
    'ATAN2': 'str',
    'ATANH': 'str',
    'AVEDEV': 'str',
    'AVERAGE': 'str',
    'AVERAGEA': 'str',
    'AVERAGEIF': 'str',
    'AVERAGEIFS': 'str',
    'BAHTTEXT': 'str',
    'BESSELI': 'str',
    'BESSELJ': 'str',
    'BESSELK': 'str',
    'BESSELY': 'str',
    'BETADIST': 'str',
    'BETAINV': 'str',
    'BIN2DEC': 'str',
    'BIN2HEX': 'str',
    'BIN2OCT': 'str',
    'BINOMDIST': 'str',
    'CEILING': 'str',
    'CELL': 'str',
    'CHAR': 'str',
    'CHIDIST': 'str',
    'CHIINV': 'str',
    'CHITEST': 'str',
    'CHOOSE': 'str',
    'CLEAN': 'str',
    'CODE': 'str',
    'COLUMN': 'str',
    'COLUMNS': 'str',
    'COMBIN': 'str',
    'COMPLEX': 'str',
    'CONCATENATE': 'str',
    'CONFIDENCE': 'str',
    'CONVERT': 'str',
    'CORREL': 'str',
    'COS': 'str',
    'COSH': 'str',
    'COUNT': 'str',
    'COUNTA': 'str',
    'COUNTBLANK': 'str',
    'COUNTIF': 'str',
    'COUNTIFS': 'str',
    'COUPDAYBS': 'str',
    'COUPDAYS': 'str',
    'COUPDAYSNC': 'str',
    'COUPNCD': 'str',
    'COUPNUM': 'str',
    'COUPPCD': 'str',
    'COVAR': 'str',
    'CRITBINOM': 'str',
    'CUBEKPIMEMBER': 'str',
    'CUBEMEMBER': 'str',
    'CUBEMEMBERPROPERTY': 'str',
    'CUBERANKEDMEMBER': 'str',
    'CUBESET': 'str',
    'CUBESETCOUNT': 'str',
    'CUBEVALUE': 'str',
    'CUMIPMT': 'str',
    'CUMPRINC': 'str',
    'DATE': 'str',
    'DATEDIF': 'str',
    'DATEVALUE': 'str',
    'DAVERAGE': 'str',
    'DAY': 'str',
    'DAYS360': 'str',
    'DB': 'str',
    'DCOUNT': 'str',
    'DCOUNTA': 'str',
    'DDB': 'str',
    'DEC2BIN': 'str',
    'DEC2HEX': 'str',
    'DEC2OCT': 'str',
    'DEGREES': 'str',
    'DELTA': 'str',
    'DEVSQ': 'str',
    'DGET': 'str',
    'DISC': 'str',
    'DMAX': 'str',
    'DMIN': 'str',
    'DOLLAR': 'str',
    'DOLLARDE': 'str',
    'DOLLARFR': 'str',
    'DPRODUCT': 'str',
    'DSTDEV': 'str',
    'DSTDEVP': 'str',
    'DSUM': 'str',
    'DURATION': 'str',
    'DVAR': 'str',
    'DVARP': 'str',
    'ECMA.CEILING': 'str',
    'EDATE': 'str',
    'EFFECT': 'str',
    'EOMONTH': 'str',
    'ERF': 'str',
    'ERFC': 'str',
    'ERROR.TYPE': 'str',
    'EVEN': 'str',
    'EXACT': 'str',
    'EXP': 'str',
    'EXPONDIST': 'str',
    'FACT': 'str',
    'FACTDOUBLE': 'str',
    'FALSE': 'str',
    'FDIST': 'str',
    'FIND': 'str',
    'FINDB': 'str',
    'FINV': 'str',
    'FISHER': 'str',
    'FISHERINV': 'str',
    'FIXED': 'str',
    'FLOOR': 'str',
    'FORECAST': 'str',
    'FREQUENCY': 'str',
    'FTEST': 'str',
    'FV': 'str',
    'FVSCHEDULE': 'str',
    'GAMMADIST': 'str',
    'GAMMAINV': 'str',
    'GAMMALN': 'str',
    'GCD': 'str',
    'GEOMEAN': 'str',
    'GESTEP': 'str',
    'GETPIVOTDATA': 'str',
    'GROWTH': 'str',
    'HARMEAN': 'str',
    'HEX2BIN': 'str',
    'HEX2DEC': 'str',
    'HEX2OCT': 'str',
    'HLOOKUP': 'str',
    'HOUR': 'str',
    'HYPERLINK': 'str',
    'HYPGEOMDIST': 'str',
    'IF': 'str',
    'IFERROR': 'str',
    'IMABS': 'str',
    'IMAGINARY': 'str',
    'IMARGUMENT': 'str',
    'IMCONJUGATE': 'str',
    'IMCOS': 'str',
    'IMDIV': 'str',
    'IMEXP': 'str',
    'IMLN': 'str',
    'IMLOG10': 'str',
    'IMLOG2': 'str',
    'IMPOWER': 'str',
    'IMPRODUCT': 'str',
    'IMREAL': 'str',
    'IMSIN': 'str',
    'IMSQRT': 'str',
    'IMSUB': 'str',
    'IMSUM': 'str',
    'INDEX': 'str',
    'INDIRECT': 'str',
    'INFO': 'str',
    'INT': 'str',
    'INTERCEPT': 'str',
    'INTRATE': 'str',
    'IPMT': 'str',
    'IRR': 'str',
    'ISBLANK': 'str',
    'ISERR': 'str',
    'ISERROR': 'str',
    'ISEVEN': 'str',
    'ISLOGICAL': 'str',
    'ISNA': 'str',
    'ISNONTEXT': 'str',
    'ISNUMBER': 'str',
    'ISO.CEILING': 'str',
    'ISODD': 'str',
    'ISPMT': 'str',
    'ISREF': 'str',
    'ISTEXT': 'str',
    'JIS': 'str',
    'KURT': 'str',
    'LARGE': 'str',
    'LCM': 'str',
    'LEFT': 'str',
    'LEFTB': 'str',
    'LEN': 'str',
    'LENB': 'str',
    'LINEST': 'str',
    'LN': 'str',
    'LOG': 'str',
    'LOG10': 'str',
    'LOGEST': 'str',
    'LOGINV': 'str',
    'LOGNORMDIST': 'str',
    'LOOKUP': 'str',
    'LOWER': 'str',
    'MATCH': 'str',
    'MAX': 'str',
    'MAXA': 'str',
    'MDETERM': 'str',
    'MDURATION': 'str',
    'MEDIAN': 'str',
    'MID': 'str',
    'MIDB': 'str',
    'MIN': 'str',
    'MINA': 'str',
    'MINUTE': 'str',
    'MINVERSE': 'str',
    'MIRR': 'str',
    'MMULT': 'str',
    'MOD': 'str',
    'MODE': 'str',
    'MONTH': 'str',
    'MROUND': 'str',
    'MULTINOMIAL': 'str',
    'N': 'str',
    'NA': 'str',
    'NEGBINOMDIST': 'str',
    'NETWORKDAYS.INTL': 'str',
    'NETWORKDAYS': 'str',
    'NOMINAL': 'str',
    'NORMDIST': 'str',
    'NORMINV': 'str',
    'NORMSDIST': 'str',
    'NORMSINV': 'str',
    'NOT': 'str',
    'NOW': 'str',
    'NPER': 'str',
    'NPV': 'str',
    'OCT2BIN': 'str',
    'OCT2DEC': 'str',
    'OCT2HEX': 'str',
    'ODD': 'str',
    'ODDFPRICE': 'str',
    'ODDFYIELD': 'str',
    'ODDLPRICE': 'str',
    'ODDLYIELD': 'str',
    'OFFSET': 'str',
    'OR': 'str',
    'PEARSON': 'str',
    'PERCENTILE': 'str',
    'PERCENTRANK': 'str',
    'PERMUT': 'str',
    'PHONETIC': 'str',
    'PI': 'str',
    'PMT': 'str',
    'POISSON': 'str',
    'POWER': 'str',
    'PPMT': 'str',
    'PRICE': 'str',
    'PRICEDISC': 'str',
    'PRICEMAT': 'str',
    'PROB': 'str',
    'PRODUCT': 'str',
    'PROPER': 'str',
    'PV': 'str',
    'QUARTILE': 'str',
    'QUOTIENT': 'str',
    'RADIANS': 'str',
    'RAND': 'str',
    'RANDBETWEEN': 'str',
    'RANK': 'str',
    'RATE': 'str',
    'RECEIVED': 'str',
    'REPLACE': 'str',
    'REPLACEB': 'str',
    'REPT': 'str',
    'RIGHT': 'str',
    'RIGHTB': 'str',
    'ROMAN': 'str',
    'ROUND': 'str',
    'ROUNDDOWN': 'str',
    'ROUNDUP': 'str',
    'ROW': 'str',
    'ROWS': 'str',
    'RSQ': 'str',
    'RTD': 'str',
    'SEARCH': 'str',
    'SEARCHB': 'str',
    'SECOND': 'str',
    'SERIESSUM': 'str',
    'SIGN': 'str',
    'SIN': 'str',
    'SINH': 'str',
    'SKEW': 'str',
    'SLN': 'str',
    'SLOPE': 'str',
    'SMALL': 'str',
    'SQRT': 'str',
    'SQRTPI': 'str',
    'STANDARDIZE': 'str',
    'STDEV STDEVA': 'str',
    'STDEVP': 'str',
    'STDEVPA STEYX': 'str',
    'SUBSTITUTE': 'str',
    'SUBTOTAL': 'str',
    'SUM': 'str',
    'SUMIF': 'str',
    'SUMIFS': 'str',
    'SUMPRODUCT': 'str',
    'SUMSQ': 'str',
    'SUMX2MY2': 'str',
    'SUMX2PY2': 'str',
    'SUMXMY2': 'str',
    'SYD': 'str',
    'T': 'str',
    'TAN': 'str',
    'TANH': 'str',
    'TBILLEQ': 'str',
    'TBILLPRICE': 'str',
    'TBILLYIELD': 'str',
    'TDIST': 'str',
    'TEXT': 'str',
    'TIME': 'str',
    'TIMEVALUE': 'str',
    'TINV': 'str',
    'TODAY': 'str',
    'TRANSPOSE': 'str',
    'TREND': 'str',
    'TRIM': 'str',
    'TRIMMEAN': 'str',
    'TRUE ADDRESS': 'str',
    'TRUNC': 'str',
    'TTEST': 'str',
    'TYPE': 'str',
    'UPPER': 'str',
    'VALUE': 'str',
    'VAR': 'str',
    'VARA': 'str',
    'VARP': 'str',
    'VARPA': 'str',
    'VDB': 'str',
    'VLOOKUP': 'str',
    'WEEKDAY': 'str',
    'WEEKNUM': 'str',
    'WEIBULL': 'str',
    'WORKDAY.INTL': 'str',
    'WORKDAY': 'str',
    'XIRR': 'str',
    'XNPV': 'str',
    'YEAR': 'str',
    'YEARFRAC': 'str',
    'YIELD': 'str',
    'YIELDDISC': 'str',
    'YIELDMAT': 'str',
    'ZTEST': 'str',

}

